// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backup-configs/database/{id}": {
            "get": {
                "description": "Get backup configuration for a specific database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup-configs"
                ],
                "summary": "Get backup configuration by database ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backups_config.BackupConfig"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/backup-configs/save": {
            "post": {
                "description": "Save or update backup configuration for a database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup-configs"
                ],
                "summary": "Save backup configuration",
                "parameters": [
                    {
                        "description": "Backup configuration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backups_config.BackupConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backups_config.BackupConfig"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/backup-configs/storage/{id}/is-using": {
            "get": {
                "description": "Check if a storage is currently being used by any backup configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup-configs"
                ],
                "summary": "Check if storage is being used",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Storage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/backups": {
            "get": {
                "description": "Get all backups for the specified database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backups"
                ],
                "summary": "Get backups for a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backups.Backup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new backup for the specified database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backups"
                ],
                "summary": "Create a backup",
                "parameters": [
                    {
                        "description": "Backup creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backups.MakeBackupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/backups/{id}": {
            "delete": {
                "description": "Delete an existing backup",
                "tags": [
                    "backups"
                ],
                "summary": "Delete a backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/backups/{id}/file": {
            "get": {
                "description": "Download the backup file for the specified backup",
                "tags": [
                    "backups"
                ],
                "summary": "Download a backup file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases": {
            "get": {
                "description": "Get all databases for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Get databases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/databases.Database"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/create": {
            "post": {
                "description": "Create a new database configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Create a new database",
                "parameters": [
                    {
                        "description": "Database creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/notifier/{id}/is-using": {
            "get": {
                "description": "Check if a notifier is currently being used by any database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Check if notifier is being used",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notifier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/test-connection-direct": {
            "post": {
                "description": "Test connection to a database configuration without saving it",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Test database connection directly",
                "parameters": [
                    {
                        "description": "Database configuration to test",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/databases/update": {
            "post": {
                "description": "Update an existing database configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Update a database",
                "parameters": [
                    {
                        "description": "Database update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/{id}": {
            "get": {
                "description": "Get a database configuration by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Get a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "delete": {
                "description": "Delete a database configuration",
                "tags": [
                    "databases"
                ],
                "summary": "Delete a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/{id}/copy": {
            "post": {
                "description": "Copy an existing database configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Copy a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/databases.Database"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/databases/{id}/test-connection": {
            "post": {
                "description": "Test connection to an existing database configuration",
                "tags": [
                    "databases"
                ],
                "summary": "Test database connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/disk/usage": {
            "get": {
                "description": "Returns information about disk space usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "disk"
                ],
                "summary": "Get disk usage information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/disk.DiskUsage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/downdetect/api": {
            "get": {
                "description": "Checks if the API service is available",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "downdetect"
                ],
                "summary": "Check API availability",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/healthcheck-attempts/{databaseId}": {
            "get": {
                "description": "Get healthcheck attempts for a specific database with optional before date filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck-attempts"
                ],
                "summary": "Get healthcheck attempts by database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "databaseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "After date (RFC3339 format)",
                        "name": "afterDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/healthcheck_attempt.HealthcheckAttempt"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/healthcheck-config": {
            "post": {
                "description": "Create or update healthcheck configuration for a database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck-config"
                ],
                "summary": "Save healthcheck configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Healthcheck configuration data",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/healthcheck_config.HealthcheckConfigDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/healthcheck-config/{databaseId}": {
            "get": {
                "description": "Get healthcheck configuration for a specific database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck-config"
                ],
                "summary": "Get healthcheck configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "databaseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck_config.HealthcheckConfig"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/notifiers": {
            "get": {
                "description": "Get all notifiers for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Get all notifiers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/notifiers.Notifier"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "description": "Create or update a notifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Save a notifier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Notifier data",
                        "name": "notifier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notifiers.Notifier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notifiers.Notifier"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/notifiers/direct-test": {
            "post": {
                "description": "Send a test notification using a notifier object provided in the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Send test notification directly",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Notifier data",
                        "name": "notifier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notifiers.Notifier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/notifiers/{id}": {
            "get": {
                "description": "Get a specific notifier by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Get a notifier by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Notifier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notifiers.Notifier"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "delete": {
                "description": "Delete a notifier by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Delete a notifier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Notifier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/notifiers/{id}/test": {
            "post": {
                "description": "Send a test notification using the specified notifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifiers"
                ],
                "summary": "Send test notification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Notifier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/restores/{backupId}": {
            "get": {
                "description": "Get all restores for a specific backup",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restores"
                ],
                "summary": "Get restores for a backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "backupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Restore"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/restores/{backupId}/restore": {
            "post": {
                "description": "Start a restore process for a specific backup",
                "tags": [
                    "restores"
                ],
                "summary": "Restore a backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "backupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/storages": {
            "get": {
                "description": "Get all storages for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Get all storages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storages.Storage"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "description": "Create or update a storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Save a storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Storage data",
                        "name": "storage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storages.Storage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storages.Storage"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/storages/direct-test": {
            "post": {
                "description": "Test the connection to a storage object provided in the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Test storage connection directly",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Storage data",
                        "name": "storage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storages.Storage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/storages/{id}": {
            "get": {
                "description": "Get a specific storage by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Get a storage by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Storage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storages.Storage"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "delete": {
                "description": "Delete a storage by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Delete a storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Storage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/storages/{id}/test": {
            "post": {
                "description": "Test the connection to the storage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storages"
                ],
                "summary": "Test storage connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Storage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/system/health": {
            "get": {
                "description": "Check if the system is healthy by testing database connection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system/health"
                ],
                "summary": "Check system health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system_healthcheck.HealthcheckResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/system_healthcheck.HealthcheckResponse"
                        }
                    }
                }
            }
        },
        "/users/admin/create-user": {
            "post": {
                "description": "Create a new user with specified role. Only accessible by admin users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/admin/list": {
            "get": {
                "description": "Get a list of all users in the system. Only accessible by admin users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/users.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/admin/{id}/password": {
            "put": {
                "description": "Change the password of a user. Only accessible by admin users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change user password (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Password change data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ChangeUserPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/admin/{id}/status": {
            "put": {
                "description": "Update the status of a user (ACTIVE/BLOCKED). Only accessible by admin users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user status (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.UpdateUserStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/is-any-user-exist": {
            "get": {
                "description": "Check if any user exists in the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Check if any user exists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current authenticated user's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users_models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/me/password": {
            "put": {
                "description": "Change the authenticated user's own password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change current user's password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Password change data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ChangeMyPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/signin": {
            "post": {
                "description": "Authenticate a user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "User signin data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/signup": {
            "post": {
                "description": "Register a new user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User signup data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    },
    "definitions": {
        "backups.Backup": {
            "type": "object",
            "properties": {
                "backupDurationMs": {
                    "type": "integer"
                },
                "backupSizeMb": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "database": {
                    "$ref": "#/definitions/databases.Database"
                },
                "databaseId": {
                    "type": "string"
                },
                "failMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/backups.BackupStatus"
                },
                "storage": {
                    "$ref": "#/definitions/storages.Storage"
                },
                "storageId": {
                    "type": "string"
                }
            }
        },
        "backups.BackupStatus": {
            "type": "string",
            "enum": [
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED"
            ],
            "x-enum-varnames": [
                "BackupStatusInProgress",
                "BackupStatusCompleted",
                "BackupStatusFailed"
            ]
        },
        "backups.MakeBackupRequest": {
            "type": "object",
            "required": [
                "database_id"
            ],
            "properties": {
                "database_id": {
                    "type": "string"
                }
            }
        },
        "backups_config.BackupConfig": {
            "type": "object",
            "properties": {
                "backupInterval": {
                    "$ref": "#/definitions/intervals.Interval"
                },
                "backupIntervalId": {
                    "type": "string"
                },
                "cpuCount": {
                    "type": "integer"
                },
                "databaseId": {
                    "type": "string"
                },
                "isBackupsEnabled": {
                    "type": "boolean"
                },
                "isRetryIfFailed": {
                    "type": "boolean"
                },
                "maxFailedTriesCount": {
                    "type": "integer"
                },
                "sendNotificationsOn": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backups_config.BackupNotificationType"
                    }
                },
                "storage": {
                    "$ref": "#/definitions/storages.Storage"
                },
                "storageId": {
                    "type": "string"
                },
                "storePeriod": {
                    "$ref": "#/definitions/period.Period"
                }
            }
        },
        "backups_config.BackupNotificationType": {
            "type": "string",
            "enum": [
                "BACKUP_FAILED",
                "BACKUP_SUCCESS"
            ],
            "x-enum-varnames": [
                "NotificationBackupFailed",
                "NotificationBackupSuccess"
            ]
        },
        "databases.Database": {
            "type": "object",
            "properties": {
                "healthStatus": {
                    "$ref": "#/definitions/databases.HealthStatus"
                },
                "id": {
                    "type": "string"
                },
                "lastBackupErrorMessage": {
                    "type": "string"
                },
                "lastBackupTime": {
                    "description": "these fields are not reliable, but\nthey are used for pretty UI",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notifiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/notifiers.Notifier"
                    }
                },
                "postgresql": {
                    "$ref": "#/definitions/postgresql.PostgresqlDatabase"
                },
                "type": {
                    "$ref": "#/definitions/databases.DatabaseType"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "databases.DatabaseType": {
            "type": "string",
            "enum": [
                "POSTGRES"
            ],
            "x-enum-varnames": [
                "DatabaseTypePostgres"
            ]
        },
        "databases.HealthStatus": {
            "type": "string",
            "enum": [
                "AVAILABLE",
                "UNAVAILABLE"
            ],
            "x-enum-varnames": [
                "HealthStatusAvailable",
                "HealthStatusUnavailable"
            ]
        },
        "discord_notifier.DiscordNotifier": {
            "type": "object",
            "properties": {
                "channelWebhookUrl": {
                    "type": "string"
                },
                "notifierId": {
                    "type": "string"
                }
            }
        },
        "disk.DiskUsage": {
            "type": "object",
            "properties": {
                "freeSpaceBytes": {
                    "type": "integer"
                },
                "platform": {
                    "$ref": "#/definitions/disk.Platform"
                },
                "totalSpaceBytes": {
                    "type": "integer"
                },
                "usedSpaceBytes": {
                    "type": "integer"
                }
            }
        },
        "disk.Platform": {
            "type": "string",
            "enum": [
                "linux",
                "windows"
            ],
            "x-enum-varnames": [
                "PlatformLinux",
                "PlatformWindows"
            ]
        },
        "email_notifier.EmailNotifier": {
            "type": "object",
            "properties": {
                "notifierId": {
                    "type": "string"
                },
                "smtpHost": {
                    "type": "string"
                },
                "smtpPassword": {
                    "type": "string"
                },
                "smtpPort": {
                    "type": "integer"
                },
                "smtpUser": {
                    "type": "string"
                },
                "targetEmail": {
                    "type": "string"
                }
            }
        },
        "enums.RestoreStatus": {
            "type": "string",
            "enum": [
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED"
            ],
            "x-enum-varnames": [
                "RestoreStatusInProgress",
                "RestoreStatusCompleted",
                "RestoreStatusFailed"
            ]
        },
        "google_drive_storage.GoogleDriveStorage": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "storageId": {
                    "type": "string"
                },
                "tokenJson": {
                    "type": "string"
                }
            }
        },
        "healthcheck_attempt.HealthcheckAttempt": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "databaseId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/databases.HealthStatus"
                }
            }
        },
        "healthcheck_config.HealthcheckConfig": {
            "type": "object",
            "properties": {
                "attemptsBeforeConcideredAsDown": {
                    "type": "integer"
                },
                "databaseId": {
                    "type": "string"
                },
                "intervalMinutes": {
                    "type": "integer"
                },
                "isHealthcheckEnabled": {
                    "type": "boolean"
                },
                "isSentNotificationWhenUnavailable": {
                    "type": "boolean"
                },
                "storeAttemptsDays": {
                    "type": "integer"
                }
            }
        },
        "healthcheck_config.HealthcheckConfigDTO": {
            "type": "object",
            "properties": {
                "attemptsBeforeConcideredAsDown": {
                    "type": "integer"
                },
                "databaseId": {
                    "type": "string"
                },
                "intervalMinutes": {
                    "type": "integer"
                },
                "isHealthcheckEnabled": {
                    "type": "boolean"
                },
                "isSentNotificationWhenUnavailable": {
                    "type": "boolean"
                },
                "storeAttemptsDays": {
                    "type": "integer"
                }
            }
        },
        "intervals.Interval": {
            "type": "object",
            "properties": {
                "dayOfMonth": {
                    "description": "only for MONTHLY",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "interval": {
                    "$ref": "#/definitions/intervals.IntervalType"
                },
                "timeOfDay": {
                    "type": "string"
                },
                "weekday": {
                    "description": "only for WEEKLY",
                    "type": "integer"
                }
            }
        },
        "intervals.IntervalType": {
            "type": "string",
            "enum": [
                "HOURLY",
                "DAILY",
                "WEEKLY",
                "MONTHLY"
            ],
            "x-enum-varnames": [
                "IntervalHourly",
                "IntervalDaily",
                "IntervalWeekly",
                "IntervalMonthly"
            ]
        },
        "local_storage.LocalStorage": {
            "type": "object",
            "properties": {
                "storageId": {
                    "type": "string"
                }
            }
        },
        "models.Restore": {
            "type": "object",
            "properties": {
                "backup": {
                    "$ref": "#/definitions/backups.Backup"
                },
                "backupId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "failMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "postgresql": {
                    "$ref": "#/definitions/postgresql.PostgresqlDatabase"
                },
                "restoreDurationMs": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/enums.RestoreStatus"
                }
            }
        },
        "nas_storage.NASStorage": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "share": {
                    "type": "string"
                },
                "storageId": {
                    "type": "string"
                },
                "useSsl": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "notifiers.Notifier": {
            "type": "object",
            "properties": {
                "discordNotifier": {
                    "$ref": "#/definitions/discord_notifier.DiscordNotifier"
                },
                "emailNotifier": {
                    "$ref": "#/definitions/email_notifier.EmailNotifier"
                },
                "id": {
                    "type": "string"
                },
                "lastSendError": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notifierType": {
                    "$ref": "#/definitions/notifiers.NotifierType"
                },
                "slackNotifier": {
                    "$ref": "#/definitions/slack_notifier.SlackNotifier"
                },
                "teamsNotifier": {
                    "$ref": "#/definitions/teams_notifier.TeamsNotifier"
                },
                "telegramNotifier": {
                    "description": "specific notifier",
                    "allOf": [
                        {
                            "$ref": "#/definitions/telegram_notifier.TelegramNotifier"
                        }
                    ]
                },
                "userId": {
                    "type": "string"
                },
                "webhookNotifier": {
                    "$ref": "#/definitions/webhook_notifier.WebhookNotifier"
                }
            }
        },
        "notifiers.NotifierType": {
            "type": "string",
            "enum": [
                "EMAIL",
                "TELEGRAM",
                "WEBHOOK",
                "SLACK",
                "DISCORD",
                "TEAMS"
            ],
            "x-enum-varnames": [
                "NotifierTypeEmail",
                "NotifierTypeTelegram",
                "NotifierTypeWebhook",
                "NotifierTypeSlack",
                "NotifierTypeDiscord",
                "NotifierTypeTeams"
            ]
        },
        "period.Period": {
            "type": "string",
            "enum": [
                "DAY",
                "WEEK",
                "MONTH",
                "3_MONTH",
                "6_MONTH",
                "YEAR",
                "2_YEARS",
                "3_YEARS",
                "4_YEARS",
                "5_YEARS",
                "FOREVER"
            ],
            "x-enum-varnames": [
                "PeriodDay",
                "PeriodWeek",
                "PeriodMonth",
                "Period3Month",
                "Period6Month",
                "PeriodYear",
                "Period2Years",
                "Period3Years",
                "Period4Years",
                "Period5Years",
                "PeriodForever"
            ]
        },
        "postgresql.PostgresqlDatabase": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string"
                },
                "databaseId": {
                    "type": "string"
                },
                "host": {
                    "description": "connection data",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isHttps": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "restoreId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "version": {
                    "$ref": "#/definitions/tools.PostgresqlVersion"
                }
            }
        },
        "s3_storage.S3Storage": {
            "type": "object",
            "properties": {
                "s3AccessKey": {
                    "type": "string"
                },
                "s3Bucket": {
                    "type": "string"
                },
                "s3Endpoint": {
                    "type": "string"
                },
                "s3Region": {
                    "type": "string"
                },
                "s3SecretKey": {
                    "type": "string"
                },
                "storageId": {
                    "type": "string"
                }
            }
        },
        "slack_notifier.SlackNotifier": {
            "type": "object",
            "properties": {
                "botToken": {
                    "type": "string"
                },
                "notifierId": {
                    "type": "string"
                },
                "targetChatId": {
                    "type": "string"
                }
            }
        },
        "storages.Storage": {
            "type": "object",
            "properties": {
                "googleDriveStorage": {
                    "$ref": "#/definitions/google_drive_storage.GoogleDriveStorage"
                },
                "id": {
                    "type": "string"
                },
                "lastSaveError": {
                    "type": "string"
                },
                "localStorage": {
                    "description": "specific storage",
                    "allOf": [
                        {
                            "$ref": "#/definitions/local_storage.LocalStorage"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "nasStorage": {
                    "$ref": "#/definitions/nas_storage.NASStorage"
                },
                "s3Storage": {
                    "$ref": "#/definitions/s3_storage.S3Storage"
                },
                "type": {
                    "$ref": "#/definitions/storages.StorageType"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "storages.StorageType": {
            "type": "string",
            "enum": [
                "LOCAL",
                "S3",
                "GOOGLE_DRIVE",
                "NAS"
            ],
            "x-enum-varnames": [
                "StorageTypeLocal",
                "StorageTypeS3",
                "StorageTypeGoogleDrive",
                "StorageTypeNAS"
            ]
        },
        "system_healthcheck.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "teams_notifier.TeamsNotifier": {
            "type": "object",
            "properties": {
                "notifierId": {
                    "type": "string"
                },
                "powerAutomateUrl": {
                    "type": "string"
                }
            }
        },
        "telegram_notifier.TelegramNotifier": {
            "type": "object",
            "properties": {
                "botToken": {
                    "type": "string"
                },
                "notifierId": {
                    "type": "string"
                },
                "targetChatId": {
                    "type": "string"
                },
                "threadId": {
                    "type": "integer"
                }
            }
        },
        "tools.PostgresqlVersion": {
            "type": "string",
            "enum": [
                "13",
                "14",
                "15",
                "16",
                "17",
                "18"
            ],
            "x-enum-varnames": [
                "PostgresqlVersion13",
                "PostgresqlVersion14",
                "PostgresqlVersion15",
                "PostgresqlVersion16",
                "PostgresqlVersion17",
                "PostgresqlVersion18"
            ]
        },
        "user_enums.UserRole": {
            "type": "string",
            "enum": [
                "ADMIN",
                "MANAGER"
            ],
            "x-enum-varnames": [
                "UserRoleAdmin",
                "UserRoleManager"
            ]
        },
        "user_enums.UserStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "BLOCKED"
            ],
            "x-enum-varnames": [
                "UserStatusActive",
                "UserStatusBlocked"
            ]
        },
        "users.ChangeMyPasswordRequest": {
            "type": "object",
            "required": [
                "currentPassword",
                "newPassword"
            ],
            "properties": {
                "currentPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "users.ChangeUserPasswordRequest": {
            "type": "object",
            "required": [
                "newPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "users.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "role": {
                    "$ref": "#/definitions/user_enums.UserRole"
                }
            }
        },
        "users.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "users.SignInResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "users.SignUpRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "users.UpdateUserStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "$ref": "#/definitions/user_enums.UserStatus"
                }
            }
        },
        "users.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/user_enums.UserRole"
                },
                "status": {
                    "$ref": "#/definitions/user_enums.UserStatus"
                }
            }
        },
        "users_models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/user_enums.UserRole"
                },
                "status": {
                    "$ref": "#/definitions/user_enums.UserStatus"
                }
            }
        },
        "webhook_notifier.WebhookMethod": {
            "type": "string",
            "enum": [
                "POST",
                "GET"
            ],
            "x-enum-varnames": [
                "WebhookMethodPOST",
                "WebhookMethodGET"
            ]
        },
        "webhook_notifier.WebhookNotifier": {
            "type": "object",
            "properties": {
                "notifierId": {
                    "type": "string"
                },
                "webhookMethod": {
                    "$ref": "#/definitions/webhook_notifier.WebhookMethod"
                },
                "webhookUrl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4005",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Postgresus Backend API",
	Description:      "API for Postgresus",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
